# Generated by Django 4.1.7 on 2023-03-29 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_remove_room_users_room_likers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='target',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='room',
            name='likers',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
