# Generated by Django 4.1.7 on 2023-03-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_target_post_room_alter_room_likers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='likers',
            new_name='users',
        ),
    ]
